.page0
.org 	00H
PA		EQU	01H
P_PA		EQU	PA
PAWAKE	EQU	02H
P_PA_WAKE	EQU	PAWAKE
PADIR	EQU	04H
P_PA_DIR	EQU	PADIR
P_PA_IO		EQU	PADIR
PB		EQU	05H
P_PB		EQU	PB
PBTYPE	EQU	06H
P_PB_TYPE	EQU	PBTYPE
PC		EQU	07H
P_PC 		EQU PC
PCDIR	EQU	08H
P_PC_IO 	EQU	PCDIR
P_PC_DIR	EQU	PCDIR
PCSEG	EQU	09H	;
P_PCSEG		EQU	PCSEG
PD		EQU	0AH
PDDIR	EQU 0BH
PADF0	EQU	0CH	;
P_PADF0		EQU	PADF0
PADF1	EQU	0DH	;
IER		EQU	0EH	
P_IER 	EQU IER
IFR		EQU	0FH	
P_IFR 		EQU IFR	
TMR0	EQU	10H	;
P_TMR0		EQU	TMR0
TMR1	EQU	12H	;
P_TMR1  	EQU	TMR1
TMR2	EQU	14H	;
TMRC	EQU	16H	;
P_TMRCTRL 	EQU TMRC
P_TMRC		EQU	TMRC
bTMR0ON    EQU	   0
bTMR1ON    EQU	   1
bLCDON	   EQU	   4
bAUDON	   EQU	   7

TMCLK	EQU	17H	;
P_TMRCLK 	EQU TMCLK
P_TMCLK 	EQU TMCLK
DIVC	EQU	18H	;
P_DIVC		EQU	DIVC
LCDCTRL	EQU	19H	;
LCDCOM	EQU	1AH	;
P_LCD_COM	EQU	LCDCOM
WDTC	EQU	1CH	;
SYSCLK	EQU	1DH	
P_SYSCLK	EQU	SYSCLK
sysclk		equ SYSCLK
HALT	EQU	1EH	;
P_HALT		EQU	HALT
AUD0	EQU	1FH	;
P_AUD		EQU	AUD0

AUDCR	EQU	20H	;
P_AUD_CTL	EQU	AUDCR
FRAME	EQU	21H	;
;BANK	EQU	23H	;
MF		EQU	2FH

SPCR	EQU	32H
SPSR	EQU	33H
SPDR	EQU	34H
PAK		EQU	3AH
PBK		EQU	3BH
PCK		EQU	3CH
LVC		EQU	3DH
FUSE	EQU	3EH

PDSEG	EQU	5CH
RFCC0	EQU	5DH
RFCC1	EQU	5EH

.ends